apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-service
  namespace: default
spec:
  ports:
  - name: webui
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrices
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: jenkins
  type: NodePort
